# Generated by Django 3.1.5 on 2021-01-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload',
            new_name='uploaded',
        ),
    ]
